stages:
  preprocess:
    cmd: python src/data_prep.py
    deps:
    - data/raw/data.csv
    - src/data_prep.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/train.csv
    params:
    - train.test_size
    - train.max_iter
    outs:
    - models/text_model.pkl

  evaluate:
    cmd: \
